"""add scene_bridge and enrich character/stage/visual

Revision ID: ab37bde7a5e2
Revises: f05ab1af29bc
Create Date: 2026-06-15 16:50:15.573905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ab37bde7a5e2'
down_revision: Union[str, Sequence[str], None] = 'f05ab1af29bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())
    # ### commands auto generated by Alembic - please adjust! ###
    if "scene_characters" not in tables:
        op.create_table('scene_characters',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('location_name', sa.String(), nullable=False),
        sa.Column('episode', sa.Integer(), nullable=False),
        sa.Column('character_name', sa.String(), nullable=False),
        sa.Column('state', sa.Text(), nullable=True),
        sa.Column('outfit', sa.Text(), nullable=True),
        sa.Column('makeup', sa.Text(), nullable=True),
        sa.Column('expression', sa.Text(), nullable=True),
        sa.Column('action', sa.Text(), nullable=True),
        sa.Column('dialogue_tone', sa.Text(), nullable=True),
        sa.Column('importance', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if "scene_props" not in tables:
        op.create_table('scene_props',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('location_name', sa.String(), nullable=False),
        sa.Column('episode', sa.Integer(), nullable=False),
        sa.Column('prop_name', sa.String(), nullable=False),
        sa.Column('placement', sa.Text(), nullable=True),
        sa.Column('in_use_by', sa.String(), nullable=True),
        sa.Column('condition', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    for table, columns in {
        "character_profiles": [
            sa.Column('nationality', sa.String(), nullable=True),
            sa.Column('precise_age', sa.Integer(), nullable=True),
            sa.Column('hairstyle', sa.Text(), nullable=True),
        ],
        "character_stages": [
            sa.Column('hair_style', sa.Text(), nullable=True),
            sa.Column('makeup_spec', sa.Text(), nullable=True),
        ],
    }.items():
        existing = {item["name"] for item in inspect(bind).get_columns(table)}
        for column in columns:
            if column.name not in existing:
                op.add_column(table, column)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_stages', 'makeup_spec')
    op.drop_column('character_stages', 'hair_style')
    op.drop_column('character_profiles', 'hairstyle')
    op.drop_column('character_profiles', 'precise_age')
    op.drop_column('character_profiles', 'nationality')
    op.drop_table('scene_props')
    op.drop_table('scene_characters')
    # ### end Alembic commands ###
