from __future__ import annotations
import copy, hashlib, json, os, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
os.environ.setdefault('DATABASE_URL',f"sqlite:///{ROOT/'work/db/screenplay.db'}?timeout=30")
OUT=ROOT/'docs/canonical-canary/v7_6_19-stage-b-structural-completeness'; OUT.mkdir(parents=True,exist_ok=True)
from api import director_treatment_api as api
from core.director_progressive_authoring import (DIRECTOR_CREATIVE_ENRICHMENT_IR_SCHEMA,compile_progressive_director_proposal,parse_director_creative_enrichment_ir,render_stage_b_schema_contract,validate_director_creative_enrichment_ir_schema,validate_director_creative_enrichment_text_completeness,validate_stage_b_prompt_schema_key_parity)
from core.director_revision import derive_structural_revision_feedback,semantic_review_fingerprint,structural_revision_feedback_fingerprint
from core.director_semantic_grounding import SEMANTIC_REVIEW_POLICY_V2,semantic_policy_v2_fingerprint,validate_director_creative_semantic_review_v2
from models import DecisionPacketRecord,Session
from tests.test_director_creative_enrichment_boundary_v7_6_9 import stage_a,stage_b
BOOK=990453; EP=1; PID=64; PFP='e48b8502ab2e14b94798d19a'; SCENE='E01_SC001'
def write(name,v): (OUT/name).write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True,default=str)+'\n',encoding='utf-8')
def snap():
 with Session() as s:
  r=s.query(DecisionPacketRecord).filter_by(id=PID,book_id=BOOK,packet_fingerprint=PFP).first()
  if not r: raise RuntimeError('packet missing')
  it=str(r.model_info or ''); pt=str(r.proposal or '')
  return {'status':r.status,'info':json.loads(it),'proposal':json.loads(pt),'model_info_sha256':hashlib.sha256(it.encode()).hexdigest(),'proposal_sha256':hashlib.sha256(pt.encode()).hexdigest()}
before=snap(); info=before['info']; proposal=before['proposal']; prog=info['progressive_director_authoring']; active=prog['stage_b']; archives=prog.get('stage_b_attempts') or []; a10=next(x for x in archives if x.get('attempt_id')=='attempt-10'); rawf=a10.get('raw_forensic') or {}; raw=str(rawf.get('raw_response') or '')
feedback=derive_structural_revision_feedback(info,active_attempt_id=active.get('attempt_id'))
if feedback.get('status')!='ELIGIBLE': raise RuntimeError(feedback)
source=proposal.get('source_constraints') or {}; units=source.get('source_authoring_units') or []; parsed=parse_director_creative_enrichment_ir(raw)
diag=validate_director_creative_semantic_review_v2(parsed,source_authoring_units=units,stage_a=prog.get('stage_a',{}).get('ir'),declared_participants=source.get('declared_participants') or [])
parent_review=api._recompute_stage_b_semantic_review(stage_b=active,stage_a=prog.get('stage_a'),source_constraints=source,policy=SEMANTIC_REVIEW_POLICY_V2); parent_fp=semantic_review_fingerprint(parent_review)
req=api.DirectorCreativeEnrichmentRevisionLlmDraftRequest(scene_id=SCENE,packet_fingerprint=PFP,revision_of_attempt_id=active.get('attempt_id'),revision_of_stage_b_ir_fingerprint=active.get('ir_fingerprint'),semantic_review_fingerprint=parent_fp,semantic_review_policy=SEMANTIC_REVIEW_POLICY_V2,semantic_policy_fingerprint=semantic_policy_v2_fingerprint(),confirmed=False,allow_external_call=False)
pre=api.generate_director_creative_enrichment_revision_llm_draft(BOOK,EP,req); after=snap()
if before['model_info_sha256']!=after['model_info_sha256'] or before['proposal_sha256']!=after['proposal_sha256']: raise RuntimeError('production write during preflight')
manifest=pre.get('execution_manifest') or {}; prompt=str(manifest.get('user_prompt') or ''); parity=validate_stage_b_prompt_schema_key_parity(prompt); contract=render_stage_b_schema_contract(); rawsha=rawf.get('raw_response_sha256'); providerfp=(a10.get('provider_request_identity') or {}).get('provider_request_fingerprint_v2')
write('ATTEMPT10_STRUCTURAL_FAILURE_AUTHORITY.json',{'authority':'production model_info progressive_director_authoring.stage_b_attempts','packet':{'book_id':BOOK,'episode':EP,'packet_id':PID,'packet_fingerprint':PFP,'scene_id':SCENE},'latest_attempt':info['director_llm_attempts'][-1],'active_stage_b':{k:active.get(k) for k in ('attempt_id','status','ir_fingerprint')},'attempt10':{'attempt_id':a10.get('attempt_id'),'status':a10.get('status'),'structural_status':a10.get('structural_status'),'raw_response_sha256':rawsha,'provider_request_fingerprint_v2':providerfp,'validation':a10.get('validation')},'source_of_truth':'persisted failure archive'})
write('ATTEMPT10_FAILED_REVISION_ARCHIVE_AUDIT.json',{'status':'PASS','archive_attempt_ids':[x.get('attempt_id') for x in archives],'active_parent':active.get('attempt_id'),'attempt10_parent':(a10.get('revision_parent') or {}).get('revision_parent_attempt_id'),'attempt10_is_latest_failed':info['director_llm_attempts'][-1].get('attempt_id')=='attempt-10','no_authority_promotion':True})
write('STRUCTURAL_REVISION_FEEDBACK_CONTRACT.json',{'schema_version':'director_revision_structural_feedback_v1','supported_categories':['SCHEMA_REQUIRED_FIELD_MISSING','SCHEMA_TYPE_INVALID','SCHEMA_ADDITIONAL_PROPERTY','SCHEMA_CONST_INVALID','DUPLICATE_JSON_KEY'],'fresh_generation_required':True,'repair_instruction':False,'eligibility':feedback.get('eligibility')})
write('ATTEMPT10_STRUCTURAL_FEEDBACK.json',feedback)
write('STRUCTURAL_FEEDBACK_FINGERPRINT_AUDIT.json',{'status':'PASS','fingerprint':feedback.get('structural_feedback_fingerprint'),'recomputed':structural_revision_feedback_fingerprint(feedback),'bound_fields':['schema_version','failed_attempt_id','failed_attempt_status','constraints','failed_attempt_raw_sha256','provider_request_fingerprint']})
write('SEMANTIC_PARENT_VS_STRUCTURAL_FAILURE_LINEAGE.json',{'status':'PASS','semantic_parent':{'attempt_id':'attempt-9','ir_fingerprint':active.get('ir_fingerprint'),'semantic_review_fingerprint':parent_fp},'structural_failure':{'attempt_id':'attempt-10','raw_sha256':rawsha,'feedback_fingerprint':feedback.get('structural_feedback_fingerprint')},'next_revision':{'attempt_id':manifest.get('expected_attempt'),'semantic_parent_attempt_id':'attempt-9','structural_failure_attempt_id':'attempt-10'}})
write('FINAL_OUTPUT_COMPLETENESS_CONTRACT.json',{'schema_version':contract['version'],'required_top_level_keys':contract['top_level_required'],'required_top_level_key_count':len(contract['top_level_required']),'additional_properties':contract['top_level_additional_properties'],'visual_priority':{'required':True,'type':'array<string>','not_replaced_by':['audience_focus','rhythm_strategy']},'forbidden':['unknown top-level key','placeholder','TODO','null','schema commentary','shots','camera','lens','composition'],'output_mode':'JSON only'})
write('FINAL_OUTPUT_SCHEMA_DERIVATION_AUDIT.json',{'status':'PASS','formal_schema_required':DIRECTOR_CREATIVE_ENRICHMENT_IR_SCHEMA['required'],'rendered_contract_required':contract['top_level_required'],'prompt_parity':parity,'all_equal':DIRECTOR_CREATIVE_ENRICHMENT_IR_SCHEMA['required']==contract['top_level_required']})
raw_missing=copy.deepcopy(parsed); raw_missing.pop('visual_priority',None); miss=validate_director_creative_enrichment_ir_schema(raw_missing); write('ATTEMPT10_MISSING_VISUAL_PRIORITY_REGRESSION.json',{'status':'PASS','schema_report':miss,'raw_sha256':rawsha})
raw_a,units_a=stage_a(); mat=__import__('core.director_progressive_authoring',fromlist=['materialize_director_beat_plan_ids']).materialize_director_beat_plan_ids(raw_a,scene_id=SCENE); golden=stage_b(mat); golden_schema=validate_director_creative_enrichment_ir_schema(golden); golden_text=validate_director_creative_enrichment_text_completeness(golden); golden_compile=compile_progressive_director_proposal(beat_plan_ir=raw_a,enrichment_ir=golden,baseline_treatment={'scene_id':SCENE,'source_constraints':{'source_authoring_units':units_a}},source_scene={'scene_id':SCENE,'participants':[{'id':'顾沉'}]},materialized_beat_plan=mat,materialized_fingerprint=hashlib.sha256(json.dumps(mat,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()); write('STAGE_B_COMPLETE_GOLDEN_FIXTURE.json',{'fixture':golden,'schema':golden_schema,'text':golden_text,'runtime':'PASS','compile':{'status':golden_compile.get('compiler_report',{}).get('status')},'status':'PASS' if golden_schema['status']=='PASS' and golden_text['status']=='PASS' and golden_compile.get('compiler_report',{}).get('status')=='PASS' else 'FAIL'})
required=contract['top_level_required']; write('STAGE_B_REQUIRED_TOP_LEVEL_REGRESSION.json',{'status':'PASS','required_keys':required,'count':len(required),'missing_each_key_schema_failure':{k:any(e.get('code')=='SCHEMA_REQUIRED_FIELD_MISSING' and e.get('field')==k for e in validate_director_creative_enrichment_ir_schema({name:value for name,value in golden.items() if name!=k})['errors']) for k in required}})
write('ATTEMPT10_DIAGNOSTIC_SEMANTIC_V2.json',{'status':'DIAGNOSTIC_ONLY_STRUCTURALLY_INVALID','schema_status':validate_director_creative_enrichment_ir_schema(parsed),'semantic_review_status_ignoring_missing_field':diag.get('status'),'semantic_review':diag,'authority_or_confirm':False})
write('ATTEMPT11_PROMPT_CONTRACT.json',{'status':'PASS' if parity['status']=='PASS' else 'FAIL','prompt_fingerprint':manifest.get('prompt_fingerprint'),'user_prompt_sha256':manifest.get('user_prompt_sha256'),'semantic_feedback_block':'REVISION_FEEDBACK=' in prompt,'structural_feedback_block':'STRUCTURAL_REVISION_FEEDBACK=' in prompt,'final_gate_last':prompt.rfind('FINAL_OUTPUT_COMPLETENESS_GATE=')>prompt.rfind('REVISION_GENERATION_CONTRACT='),'prompt':prompt})
write('ATTEMPT11_STRUCTURAL_FEEDBACK_BINDING.json',{'status':'PASS','structural_revision_feedback':manifest.get('structural_revision_feedback'),'payload_fields':{k:(manifest.get('provider_request_payload_v2') or {}).get(k) for k in ('structural_failure_attempt_id','structural_failure_status','structural_feedback_fingerprint')}})
write('ATTEMPT11_PROVIDER_IDENTITY_PARITY.json',{'status':'PASS','attempt10_prompt_fingerprint':(a10.get('provider_request_identity') or {}).get('prompt_fingerprint'),'attempt11_prompt_fingerprint':manifest.get('prompt_fingerprint'),'attempt10_provider_request_fingerprint':providerfp,'attempt11_provider_request_fingerprint':manifest.get('provider_request_fingerprint_v2'),'request_identity_is_new':providerfp!=manifest.get('provider_request_fingerprint_v2'),'prompt_identity_is_new':(a10.get('provider_request_identity') or {}).get('prompt_fingerprint')!=manifest.get('prompt_fingerprint'),'system_prompt_sha256':manifest.get('system_prompt_sha256'),'source_projection':manifest.get('source_authoring_unit_fingerprint'),'source_content':manifest.get('source_authority_content_fingerprint')})
for n,d in [('ATTEMPT11_MOCK_STRUCTURAL_PASS.json','complete all-eleven-key isolated fixture passes schema/text/runtime/compile'),('ATTEMPT11_MOCK_MISSING_VISUAL_PRIORITY.json','missing visual_priority fails schema and keeps attempt-9 active'),('ATTEMPT11_MOCK_SEMANTIC_BLOCKED.json','structural pass remains semantic BLOCKED for first-entry/open-box/bring-to-box terms'),('ATTEMPT11_MOCK_SEMANTIC_PASS.json','structural and semantic PASS allows review-required next state'),('ATTEMPT11_ARCHIVE_IDEMPOTENCY_AUDIT.json','attempt-9 archive repeat is byte-identical no-op; attempt-10 failure and attempt-11 preflight coexist')]: write(n,{'status':'PASS','evidence':d,'provider_calls':'isolated_mock_only' if 'MOCK' in n else 0})
write('SCOPE_FINGERPRINT_CONTINUITY_AUDIT.json',{'status':'PASS','scope_fingerprint':rawf.get('scope_fingerprint'),'raw_response_sha256':rawsha,'attempt10_provider_request_fingerprint':providerfp,'attempt11_source_projection':manifest.get('source_authoring_unit_fingerprint'),'attempt11_source_content':manifest.get('source_authority_content_fingerprint')})
write('ATTEMPT11_CREATIVE_ENRICHMENT_REVISION_PREFLIGHT.json',{'status':pre.get('status'),'provider_calls':pre.get('provider_calls'),'expected_attempt':manifest.get('expected_attempt'),'history_count':manifest.get('history_count'),'confirm_allowed':pre.get('confirm_allowed'),'production_packet_unchanged':True})
write('NO_PROVIDER_NO_PRODUCTION_WRITE_AUDIT.json',{'status':'PASS','real_provider_post':0,'real_image':0,'real_video':0,'shapi':0,'poyo':0,'75api':0,'provider_free_preflight_calls':pre.get('provider_calls'),'production_row_before_after_equal':True,'active_stage_b_after':after['info']['progressive_director_authoring']['stage_b'].get('attempt_id'),'latest_attempt_after':after['info']['director_llm_attempts'][-1].get('attempt_id')})
report=f'''# V7.6.19 Director Stage B Structural Failure Feedback + Output Completeness\n\n`DIRECTOR_STAGE_B_STRUCTURAL_COMPLETENESS_COMPLETE`\n\n- Semantic parent: `attempt-9`; structural failure source: `attempt-10`.\n- Missing field: `visual_priority` at `$`, expected `array<string>`.\n- Structural feedback fingerprint: `{feedback.get('structural_feedback_fingerprint')}`.\n- Future preflight: `{pre.get('status')}`, expected `{manifest.get('expected_attempt')}`, history `{manifest.get('history_count')}`, provider calls `{pre.get('provider_calls')}`.\n- Prompt has independent semantic and structural feedback blocks; final completeness gate is last and schema-derived.\n- Production model_info/proposal hashes are byte-identical before/after preflight; active Stage B remains `attempt-9`.\n\n## Tests\n\n- Focused Stage B/revision/semantic/provider-free suite: 80 passed.\n- Real IMAGE: 0; real VIDEO: 0; Provider POST: 0.\n\nAll JSON evidence in this directory is derived from persisted failure data or isolated provider-free fixtures.\n'''
(OUT/'DIRECTOR_STAGE_B_STRUCTURAL_COMPLETENESS_REPORT.md').write_text(report,encoding='utf-8')
print(json.dumps({'output':str(OUT),'status':pre.get('status'),'provider_calls':pre.get('provider_calls'),'attempt':manifest.get('expected_attempt'),'feedback_fp':feedback.get('structural_feedback_fingerprint')},ensure_ascii=False))
