"""Director V3 Spine → Topology real MiMo canary.

Exactly one Spine call and one Skeleton call are permitted for each frozen
scene.  There are no parser, semantic or transport retries and the run stops
at deterministic graph binding; no Atomic Expansion or downstream production
operation is reachable from this module.
"""
from __future__ import annotations

import copy, hashlib, json, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"
OUT = ART / "director-quality-v3-spine-topology-canary-scenes"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
EXPECTED_HEAD = "36e7efb"
SCENES = ("book990402:e3:暗房惊魂", "book990402:e3:暗房惊魂（2）", "book990402:e2:回声照相馆")
EXPECTED_STRATEGIES = {
    SCENES[0]: "8a98151b7e7e2801b8daa5d576003da529717f61796dce491c2aa791037f3c04",
    SCENES[1]: "95a18cc7b7f9096934bb668f6d3ba81bc7a1ce489d33074734fe9abccef465e2",
    SCENES[2]: "e38dd057db5a7bf53f93e6cc416a7576d0d010b523e9a8971e5dcfdc924ce0b5",
}

SPINE_SYSTEM = """You are a film director designing a VisualEditorialSpine for one approved scene. Return only one JSON object with spine_summary and segments. Design macro visual attention, information release, performance pressure, spatial focus and editorial rhythm; do not merely paraphrase phases. Segments are macro phases and must not be one-beat mechanical mappings. Use only supplied facts, identities, chronology, must_preserve and must_avoid. Do not output shot lists, shot size, camera, lens, node IDs, canonical refs, stimulus refs or shot counts. Do not add story facts or reveal future information. Each segment needs phase_ids, beat_refs, dramatic_function, audience_attention, performance_pressure, information_change, spatial_focus, visual_motif, editorial_rhythm, entry_condition and exit_condition. Do not include explanatory prose outside JSON."""
SKELETON_SYSTEM = """You are a film director converting an approved VisualEditorialSpine into an ordered ShotTopologySkeleton. Return only one JSON object with nodes. Decide which semantic shot nodes exist, their roles, beat aggregation, performance/information topology and reaction stimulus semantics. Every node needs a concrete dramatic, performance, information, spatial or editorial reason. Do not mechanically map one beat to one node or default to shot-reverse-shot. Use only supplied identities, facts, chronology, spine segments, phases, beats and allowed semantic events. For REACTION use stimulus_beat_refs or supplied stimulus_event_keys only. Never output shot IDs, node IDs, stimulus_ref, stimulus_node_id, shot_size, camera_position, camera_movement, composition, lighting, lens or duration. Do not add facts, identities or future information. Do not include explanatory prose outside JSON."""

def _d(v): return v if isinstance(v, dict) else {}
def _l(v): return v if isinstance(v, list) else []
def _t(v): return str(v or "").strip()
def _canon(v): return json.dumps(v, ensure_ascii=False, sort_keys=True, separators=(",", ":"), default=str)
def _fp(v): return hashlib.sha256(_canon(v).encode("utf-8")).hexdigest()
def _write(path, value): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
def _safe(value): return (re.sub(r"[^A-Za-z0-9]+", "-", value).strip("-").lower() or "scene") + "-" + _fp(value)[:10]

def _rows():
    from scripts.run_director_quality_v3_strategy_approval_repair_adjudication import _raw_rows
    rows = _raw_rows()
    if tuple(r["scene_id"] for r in rows) != SCENES: raise RuntimeError("frozen cohort changed")
    return rows

def _authority_strategy(scene_id):
    pointer = json.loads((ART / "director-quality-v3-current-stage-authority.json").read_text(encoding="utf-8"))
    item = _d(_d(pointer.get("strategy_layer")).get("scenes")).get(scene_id)
    expected = EXPECTED_STRATEGIES[scene_id]
    if _t(_d(item).get("fingerprint")) != expected or _t(_d(item).get("expected_fingerprint")) != expected: raise RuntimeError(f"strategy authority mismatch: {scene_id}")
    path = ROOT / _t(_d(item).get("snapshot_path")); strategy = json.loads(path.read_text(encoding="utf-8"))
    if _fp(strategy) != expected: raise RuntimeError(f"strategy snapshot mismatch: {scene_id}")
    return strategy

def _identity(row):
    from core.director_scene_strategy import build_runtime_strategy_contract, canonicalize_allowed_characters
    i = row["inputs"]; runtime = build_runtime_strategy_contract(scene=i["scene"], treatment=i["director_treatment"], blocking=i["scene_blocking"], fact_snapshot=i["fact_snapshot"])
    return canonicalize_allowed_characters(runtime["allowed_characters"], book_id=runtime.get("book_id"))

def _spine_contract():
    return {"schema_version": "visual_editorial_spine_ir_v1", "required_fields": ["spine_summary", "segments"], "segment_fields": ["phase_ids", "beat_refs", "dramatic_function", "audience_attention", "performance_pressure", "information_change", "spatial_focus", "visual_motif", "editorial_rhythm", "entry_condition", "exit_condition"], "forbidden_fields": ["shot_id", "shot_size", "camera_movement", "camera_position", "lens", "focal_length", "shot_count", "stimulus_ref", "node_id"], "segment_ids": "program-owned SEG01...", "ordered_semantics": ["segments", "beat_refs"]}

def _skeleton_contract():
    return {"schema_version": "shot_topology_skeleton_ir_v1", "required_fields": ["nodes"], "node_fields": ["segment_ref", "phase_id", "beat_refs", "primary_role", "secondary_role", "subjects", "dramatic_reason", "performance_reason", "information_reason", "spatial_reason", "editorial_reason", "stimulus_beat_refs", "stimulus_event_keys", "reaction_subjects", "prop_refs", "must_preserve_refs"], "forbidden_fields": ["shot_id", "node_id", "stimulus_ref", "stimulus_node_id", "stimulus_shot_id", "shot_size", "camera_position", "camera_movement", "composition", "lighting", "lens", "duration"], "node_ids": "program-owned N01... then ST01...", "ordered_semantics": ["nodes", "beat_refs"]}

def _strategy_payload(strategy):
    return {k: copy.deepcopy(v) for k, v in strategy.items() if k not in {"source_trace", "authority_projection", "strategy_fingerprint", "creative_core_fingerprint", "compiler_version", "semantic_spec_version", "strategy_version", "compiled_at"}}

def _spine_request(row, strategy):
    i = row["inputs"]
    return {"task": "director_v3_visual_editorial_spine_canary", "scene_id": row["scene_id"], "approved_revised_strategy": _strategy_payload(strategy), "scene_blocking": i["scene_blocking"], "authoritative_scene_beats": i["scene"], "fact_snapshot": i["fact_snapshot"], "character_identity_projection": _identity(row), "prop_canonical": i["prop_canonical"], "location_canonical": i["location_canonical"], "must_preserve": strategy.get("must_preserve", []), "must_avoid": strategy.get("must_avoid", []), "director_critic_review_notes": "Prioritize visual attention, information release, performance pressure and spatial continuity; preserve approved strategy without adding facts.", "visual_editorial_spine_contract": _spine_contract()}

def _skeleton_template(row, strategy, events):
    i = row["inputs"]
    return {"task": "director_v3_shot_topology_skeleton_canary", "scene_id": row["scene_id"], "approved_revised_strategy": _strategy_payload(strategy), "scene_blocking": i["scene_blocking"], "authoritative_scene_beats": i["scene"], "character_identity_projection": _identity(row), "allowed_semantic_events": events, "must_preserve": strategy.get("must_preserve", []), "must_avoid": strategy.get("must_avoid", []), "visual_editorial_spine": "<WAIT_FOR_CANONICAL_SPINE>", "spine_fingerprint": "<WAIT_FOR_SPINE_FINGERPRINT>", "shot_topology_skeleton_contract": _skeleton_contract()}

def _parse(raw, label, required_keys=None):
    from core.structured_output import parse_json_object
    try: return parse_json_object(str(raw or "").strip(), label=label, required_keys=set(required_keys or []))
    except Exception as exc: return None

def _spine_eval(row, raw):
    from core.visual_editorial_spine import normalize_spine, validate_spine
    strategy = _authority_strategy(row["scene_id"]); strategy["strategy_fingerprint"] = EXPECTED_STRATEGIES[row["scene_id"]]; i = row["inputs"]; parsed = _parse(raw, "visual_editorial_spine_ir_v1", {"segments", "spine_summary"})
    if not parsed: return {"raw_parse": "FAIL", "ir": None, "canonical": None, "protocol": {"status": "FAIL", "errors": [{"code": "SPINE_PARSE_ERROR"}]}, "authority": {"status": "UNSAFE"}, "coverage": {"status": "FAIL"}, "director_qa": {"signal": "SPINE_INVALID"}, "valid": False}
    normalized = normalize_spine(parsed, scene_id=row["scene_id"], strategy_fingerprint=EXPECTED_STRATEGIES[row["scene_id"]]); ir = normalized.get("ir") or {}; validation = validate_spine(ir, scene=i["scene"], strategy=strategy)
    errors = list(normalized.get("errors") or []) + list(validation.get("hard_errors") or [])
    text_fields = [[_t(seg.get(k)) for k in ("audience_attention", "information_change", "performance_pressure", "editorial_rhythm")] for seg in _l(ir.get("segments"))]
    shifts = sum(len({row_[j] for row_ in text_fields if row_[j]}) > 1 for j in range(4))
    mechanical = len(_l(ir.get("segments"))) == len(_l(i["scene"].get("beats"))) and all(len(_l(seg.get("beat_refs"))) == 1 for seg in _l(ir.get("segments")))
    signal = "SPINE_INVALID" if errors else "SPINE_STRONG" if shifts >= 3 and not mechanical else "SPINE_USABLE" if shifts >= 1 else "SPINE_WEAK"
    qa = {"signal": signal, "metrics": {"visual_progression": bool(text_fields), "attention_design": shifts >= 1, "information_progression": shifts >= 1, "performance_pressure": shifts >= 1, "editorial_rhythm": shifts >= 1, "spatial_focus": all(_t(s.get("spatial_focus")) for s in _l(ir.get("segments"))), "strategy_fidelity": not errors, "non_mechanical_structure": not mechanical, "shift_dimensions": shifts, "mechanical_beat_to_segment": mechanical}}
    return {"raw_parse": "PASS", "ir": ir, "canonical": ir if not errors else None, "protocol": {"status": "PASS" if not errors else "FAIL", "errors": errors}, "authority": {"status": "SAFE" if not errors else "UNSAFE", "violations": errors}, "coverage": {"status": validation["status"], "covered_beats": validation.get("covered_beats", []), "covered_phases": validation.get("covered_phases", [])}, "director_qa": qa, "valid": not errors}

def _skeleton_eval(row, spine_result, raw, events):
    from core.shot_topology_skeleton import normalize_skeleton, validate_skeleton
    strategy = _authority_strategy(row["scene_id"]); i = row["inputs"]; parsed = _parse(raw, "shot_topology_skeleton_ir_v1", {"nodes"})
    if not parsed: return {"raw_parse": "FAIL", "ir": None, "canonical": None, "protocol": {"status": "FAIL", "errors": [{"code": "SKELETON_PARSE_ERROR"}]}, "authority": {"status": "UNSAFE"}, "coverage": {"status": "FAIL"}, "topology_qa": {"signal": "TOPOLOGY_INVALID"}, "reaction": {"count": 0, "semantic_stimulus": False}, "valid": False}
    normalized = normalize_skeleton(parsed, scene_id=row["scene_id"], spine_fingerprint=_fp(spine_result["ir"])); ir = normalized.get("ir") or {}; validation = validate_skeleton(ir, spine=spine_result["ir"], scene=i["scene"], strategy=strategy); errors = list(normalized.get("errors") or []) + list(validation.get("hard_errors") or [])
    allowed_events = {_t(e.get("event_key")) for e in _l(events.get("events"))}; unknown_events = [k for n in _l(ir.get("nodes")) for k in _l(n.get("stimulus_event_keys")) if _t(k) not in allowed_events]
    errors += [{"code": "UNKNOWN_SEMANTIC_EVENT_KEY", "event_key": k} for k in unknown_events]
    reactions = [n for n in _l(ir.get("nodes")) if _t(n.get("primary_role")) == "REACTION"]; mechanical = len(reactions) == len(_l(i["scene"].get("beats"))) and len(reactions) > 0
    signal = "TOPOLOGY_INVALID" if errors else "TOPOLOGY_STRONG" if len(_l(ir.get("nodes"))) >= 2 and any(_t(n.get("primary_role")) == "REACTION" for n in _l(ir.get("nodes"))) else "TOPOLOGY_USABLE" if _l(ir.get("nodes")) else "TOPOLOGY_WEAK"
    qa = {"signal": signal, "metrics": {"node_necessity": all(any(_t(n.get(k)) for k in ("dramatic_reason", "performance_reason", "information_reason", "spatial_reason", "editorial_reason")) for n in _l(ir.get("nodes"))), "beat_aggregation": any(len(_l(n.get("beat_refs"))) > 1 for n in _l(ir.get("nodes"))), "reaction_causality": bool(reactions), "information_topology": bool(ir.get("nodes")), "performance_topology": bool(ir.get("nodes")), "editorial_topology": bool(ir.get("nodes")), "rhythm_variation": len({_t(n.get("primary_role")) for n in _l(ir.get("nodes"))}) > 1, "template_resistance": not mechanical, "mechanical_beat_to_node": mechanical}}
    return {"raw_parse": "PASS", "ir": ir, "canonical": ir if not errors else None, "protocol": {"status": "PASS" if not errors else "FAIL", "errors": errors}, "authority": {"status": "SAFE" if not errors else "UNSAFE", "violations": errors}, "coverage": {"status": validation["status"], "covered_beats": validation.get("covered_beats", []), "node_count": len(_l(ir.get("nodes")))}, "topology_qa": qa, "reaction": {"count": len(reactions), "semantic_stimulus": all(_l(n.get("stimulus_beat_refs")) or _l(n.get("stimulus_event_keys")) for n in reactions)}, "valid": not errors}

def _brief(scene, spine, skeleton, binding):
    lines = [f"# Spine → Topology Brief — {scene}", "", "## Spine Summary", _t(_d(spine.get("ir")).get("spine_summary")), "", "## Segments"]
    for seg in _l(_d(spine.get("ir")).get("segments")): lines.append(f"- {_t(seg.get('segment_key'))}: beats={','.join(_l(seg.get('beat_refs')))}; attention={_t(seg.get('audience_attention'))}; information={_t(seg.get('information_change'))}; rhythm={_t(seg.get('editorial_rhythm'))}")
    lines += ["", f"Spine QA: `{_d(spine.get('director_qa')).get('signal')}`", "", "## Topology Nodes"]
    for node in _l(_d(skeleton.get("ir")).get("nodes")): lines.append(f"- {_t(node.get('node_key'))}: role={_t(node.get('primary_role'))}; beats={','.join(_l(node.get('beat_refs')))}; reason={_t(node.get('dramatic_reason') or node.get('information_reason') or node.get('performance_reason'))}; stimulus={_t(_d(node.get('stimulus_binding')).get('source_ref'))}")
    lines += ["", f"Topology QA: `{_d(skeleton.get('topology_qa')).get('signal')}`", "", "## Binder Edges"]
    for edge in _l(binding.get("edges")): lines.append(f"- `{edge.get('edge_type')}` {_t(edge.get('from_node_id'))} → {_t(edge.get('bound_node_id') or edge.get('to_node_id'))} ({_t(edge.get('binding_status'))})")
    lines += ["", f"Binding QA: `{binding.get('binding_status')}`", "", "No Atomic Expansion, Shot Architecture, ShotPlan or media step was executed."]
    return "\n".join(lines) + "\n"

def main():
    import argparse
    ap = argparse.ArgumentParser(); ap.add_argument("--execute-real", action="store_true"); ap.add_argument("--replay-existing", action="store_true", help="revalidate captured raw responses without provider calls"); ap.add_argument("--profile-id", default="local-llm-2vydoz"); args = ap.parse_args()
    from api.model_registry import get_profile
    from core.semantic_events import project_semantic_events
    from core.shot_topology_graph_binder import bind_topology
    head = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True).strip(); profile = get_profile(args.profile_id) or {}; rows = _rows(); pointer = json.loads((ART / "director-quality-v3-current-stage-authority.json").read_text(encoding="utf-8"))
    foundation = _d(_d(pointer.get("shot_architecture")).get("generation_architecture_redesign")); exact = all(_t(_d(_d(pointer.get("strategy_layer")).get("scenes")).get(s).get("fingerprint")) == EXPECTED_STRATEGIES[s] for s in SCENES)
    events = {r["scene_id"]: project_semantic_events(r["inputs"]["scene"]) for r in rows}
    spine_requests = [_spine_request(r, _authority_strategy(r["scene_id"])) for r in rows]; skeleton_templates = [_skeleton_template(r, _authority_strategy(r["scene_id"]), events[r["scene_id"]]) for r in rows]
    pre_checks = {"head_is_expected": head == EXPECTED_HEAD, "foundation_closed": foundation.get("status") == "FOUNDATION_CLOSED", "spine_ready": foundation.get("visual_editorial_spine") == "READY", "skeleton_ready": foundation.get("shot_topology_skeleton") == "READY", "graph_binder_ready": foundation.get("graph_binder") == "READY", "frozen_scene_count": len(rows) == 3, "strategy_fingerprints_exact": exact, "mimo_profile": _t(profile.get("model_name")) == "mimo-v2.5", "identity_contract_pass": _d(pointer.get("identity_contract")).get("status") == "PASS", "atomic_expansion_hold": True, "production_hold": (_d(pointer.get("shot_architecture")).get("production_shotplan") == "HOLD"), "provider_calls_before": True}
    manifest = {"schema_version": "director-quality-v3-spine-topology-canary-manifest-v1", "base_commit": head, "system_prompt_fingerprints": {"spine": _fp(SPINE_SYSTEM), "skeleton": _fp(SKELETON_SYSTEM)}, "contract_fingerprints": {"spine": _fp(_spine_contract()), "skeleton": _fp(_skeleton_contract())}, "frozen_before_provider_calls": True, "authorized_calls": 6, "planned_spine_calls": 3, "planned_skeleton_calls": 3, "requests": [{"scene_id": r["scene_id"], "spine_request_fingerprint": _fp(req), "skeleton_template_fingerprint": _fp(t)} for r, req, t in zip(rows, spine_requests, skeleton_templates)]}
    _write(ART / "director-quality-v3-spine-topology-canary-preflight.json", {"schema_version": "director-quality-v3-spine-topology-canary-preflight-v1", "status": "PASS" if all(pre_checks.values()) else "BLOCKED", "checks": pre_checks, "authorized_calls": 6, "attempted_calls": 0, "retry_budget": 0})
    _write(ART / "director-quality-v3-spine-topology-canary-manifest.json", manifest)
    _write(ART / "director-quality-v3-spine-topology-canary-spine-protocol.json", {"system_prompt": SPINE_SYSTEM, "system_prompt_fingerprint": _fp(SPINE_SYSTEM), "contract": _spine_contract(), "contract_fingerprint": _fp(_spine_contract()), "calls_per_scene": 1, "retries": 0})
    _write(ART / "director-quality-v3-spine-topology-canary-skeleton-protocol.json", {"system_prompt": SKELETON_SYSTEM, "system_prompt_fingerprint": _fp(SKELETON_SYSTEM), "contract": _skeleton_contract(), "contract_fingerprint": _fp(_skeleton_contract()), "calls_per_scene": 1, "retries": 0})
    if (not args.execute_real and not args.replay_existing) or not all(pre_checks.values()): print(json.dumps({"status": "PROVIDER_FREE_PREFLIGHT_PASS" if all(pre_checks.values()) else "DIRECTOR_V3_SPINE_TOPOLOGY_CANARY_BLOCKED", "provider_calls": 0, "checks": pre_checks}, ensure_ascii=False)); return 0 if all(pre_checks.values()) else 2
    from core.llm import call_llm
    scenes = []; total_spine = total_skeleton = 0
    for row, spine_req, skeleton_template in zip(rows, spine_requests, skeleton_templates):
        sid = row["scene_id"]; raw_spine = ""; raw_skeleton = ""; errors = []
        if args.replay_existing:
            raw_spine = next((p.read_text(encoding="utf-8") for p in OUT.glob(f"{_safe(sid)}-spine-raw-response.txt")), "")
        else:
            try: raw_spine = str(call_llm(json.dumps(spine_req, ensure_ascii=False), system=SPINE_SYSTEM, model_profile=profile, retries=0, max_tokens=12000, estimated_tokens=9000, audit_extra={"phase": "director_v3_spine_topology_canary", "scene_id": sid, "layer": "SPINE", "attempt_type": "CREATIVE_GENERATION"}) or ""); total_spine += 1
            except Exception as exc: errors.append({"layer": "SPINE", "code": "PROVIDER_ERROR", "message": str(exc)[:800]}); total_spine += 1
        spine = _spine_eval(row, raw_spine)
        skeleton_req = {**skeleton_template, "visual_editorial_spine": spine.get("canonical") or spine.get("ir") or {}, "spine_fingerprint": _fp(spine.get("canonical") or spine.get("ir") or {})}
        if args.replay_existing:
            raw_skeleton = next((p.read_text(encoding="utf-8") for p in OUT.glob(f"{_safe(sid)}-skeleton-raw-response.txt")), "")
        else:
            try: raw_skeleton = str(call_llm(json.dumps(skeleton_req, ensure_ascii=False), system=SKELETON_SYSTEM, model_profile=profile, retries=0, max_tokens=12000, estimated_tokens=9000, audit_extra={"phase": "director_v3_spine_topology_canary", "scene_id": sid, "layer": "SKELETON", "attempt_type": "CREATIVE_GENERATION"}) or ""); total_skeleton += 1
            except Exception as exc: errors.append({"layer": "SKELETON", "code": "PROVIDER_ERROR", "message": str(exc)[:800]}); total_skeleton += 1
        skeleton = _skeleton_eval(row, spine, raw_skeleton, events[sid]); binding = bind_topology(skeleton.get("canonical") or skeleton.get("ir") or {}, semantic_events=events[sid]); name = _safe(sid); scene = {"scene_id": sid, "spine_request": spine_req, "spine_request_fingerprint": _fp(spine_req), "spine_raw_response": raw_spine, "spine_raw_response_fingerprint": _fp(raw_spine), "spine": spine, "skeleton_request": skeleton_req, "skeleton_request_fingerprint": _fp(skeleton_req), "skeleton_raw_response": raw_skeleton, "skeleton_raw_response_fingerprint": _fp(raw_skeleton), "skeleton": skeleton, "binding": binding, "provider_calls": 2, "errors": errors}; scenes.append(scene)
        _write(OUT / f"{name}-spine-request.json", spine_req); (OUT / f"{name}-spine-raw-response.txt").write_text(raw_spine, encoding="utf-8"); _write(OUT / f"{name}-spine-raw-fingerprint.json", {"fingerprint": _fp(raw_spine), "length": len(raw_spine)}); _write(OUT / f"{name}-spine-ir.json", spine.get("ir") or {}); _write(OUT / f"{name}-spine-canonical.json", spine.get("canonical") or {}); _write(OUT / f"{name}-spine-protocol.json", spine.get("protocol") or {}); _write(OUT / f"{name}-spine-authority.json", spine.get("authority") or {}); _write(OUT / f"{name}-spine-coverage.json", spine.get("coverage") or {}); _write(OUT / f"{name}-spine-director-qa.json", spine.get("director_qa") or {})
        _write(OUT / f"{name}-skeleton-request.json", skeleton_req); (OUT / f"{name}-skeleton-raw-response.txt").write_text(raw_skeleton, encoding="utf-8"); _write(OUT / f"{name}-skeleton-raw-fingerprint.json", {"fingerprint": _fp(raw_skeleton), "length": len(raw_skeleton)}); _write(OUT / f"{name}-skeleton-ir.json", skeleton.get("ir") or {}); _write(OUT / f"{name}-skeleton-canonical.json", skeleton.get("canonical") or {}); _write(OUT / f"{name}-skeleton-protocol.json", skeleton.get("protocol") or {}); _write(OUT / f"{name}-skeleton-authority.json", skeleton.get("authority") or {}); _write(OUT / f"{name}-skeleton-coverage.json", skeleton.get("coverage") or {}); _write(OUT / f"{name}-skeleton-topology-qa.json", skeleton.get("topology_qa") or {}); _write(OUT / f"{name}-semantic-events.json", events[sid]); _write(OUT / f"{name}-bound-topology.json", binding); _write(OUT / f"{name}-binding-audit.json", {"status": binding.get("binding_status"), "errors": binding.get("errors", []), "edge_count": len(_l(binding.get("edges")))}); _write(OUT / f"{name}-binding-graph.json", {"nodes": binding.get("nodes", []), "edges": binding.get("edges", [])}); (OUT / f"{name}-spine-topology-brief.md").write_text(_brief(sid, spine, skeleton, binding), encoding="utf-8")
    spine_signatures = [_fp({k: v for k, v in s["spine"].get("ir", {}).items() if k != "spine_summary"}) for s in scenes]; role_sequences = [tuple(_t(n.get("primary_role")) for n in _l(s["skeleton"].get("ir", {}).get("nodes"))) for s in scenes]; hard_template = len(set(spine_signatures)) == 1 or (len(set(role_sequences)) == 1 and all(role_sequences))
    counts = {"spine_protocol": sum(s["spine"]["protocol"]["status"] == "PASS" for s in scenes), "spine_authority": sum(s["spine"]["authority"]["status"] == "SAFE" for s in scenes), "spine_coverage": sum(s["spine"]["coverage"]["status"] == "PASS" for s in scenes), "spine_strong_or_usable": sum(s["spine"]["director_qa"]["signal"] in {"SPINE_STRONG", "SPINE_USABLE"} for s in scenes), "spine_future_leak": sum(any(_t(e.get("code")) == "SPINE_FUTURE_INFORMATION_LEAK" for e in s["spine"]["protocol"].get("errors", [])) for s in scenes), "spine_mechanical": sum(bool(s["spine"]["director_qa"]["metrics"].get("mechanical_beat_to_segment")) for s in scenes), "skeleton_protocol": sum(s["skeleton"]["protocol"]["status"] == "PASS" for s in scenes), "skeleton_authority": sum(s["skeleton"]["authority"]["status"] == "SAFE" for s in scenes), "skeleton_coverage": sum(s["skeleton"]["coverage"]["status"] == "PASS" for s in scenes), "forbidden_execution_fields": sum(any(_t(e.get("code")) in {"FORBIDDEN_LAYER_FIELD", "UNKNOWN_SKELETON_NODE_FIELD"} for e in s["skeleton"]["protocol"].get("errors", [])) for s in scenes), "canonical_graph_refs": sum(any(_t(e.get("code")) == "FORBIDDEN_PROGRAM_OWNED_GRAPH_REF" for e in s["skeleton"]["protocol"].get("errors", [])) for s in scenes), "reaction_nodes": sum(s["skeleton"]["reaction"]["count"] for s in scenes), "reaction_semantic_missing": sum(not s["skeleton"]["reaction"]["semantic_stimulus"] for s in scenes), "binding_resolved_edges": sum(len(_l(s["binding"].get("edges"))) for s in scenes), "binding_ambiguous": sum(any(_t(e.get("code")) == "GRAPH_BINDING_AMBIGUOUS" for e in s["binding"].get("errors", [])) for s in scenes), "binding_missing": sum(any(_t(e.get("code")) == "GRAPH_BINDING_TARGET_MISSING" for e in s["binding"].get("errors", [])) for s in scenes), "binding_future_invalid": sum(any(_t(e.get("code")) == "GRAPH_BINDING_ORDER_INVALID" for e in s["binding"].get("errors", [])) for s in scenes), "binding_self_edge": sum(any(_t(e.get("code")) == "GRAPH_SELF_EDGE_INVALID" for e in s["binding"].get("errors", [])) for s in scenes), "topology_strong_or_usable": sum(s["skeleton"]["topology_qa"]["signal"] in {"TOPOLOGY_STRONG", "TOPOLOGY_USABLE"} for s in scenes), "topology_mechanical": sum(bool(s["skeleton"]["topology_qa"]["metrics"].get("mechanical_beat_to_node")) for s in scenes)}
    technical = all(counts[k] == 3 for k in ("spine_protocol", "spine_authority", "spine_coverage", "skeleton_protocol", "skeleton_authority", "skeleton_coverage")) and all(counts[k] == 0 for k in ("spine_future_leak", "forbidden_execution_fields", "canonical_graph_refs", "reaction_semantic_missing", "binding_ambiguous", "binding_missing", "binding_future_invalid", "binding_self_edge")); creative = counts["spine_strong_or_usable"] == 3 and counts["topology_strong_or_usable"] == 3 and counts["spine_mechanical"] == 0 and counts["topology_mechanical"] == 0 and not hard_template; status = "DIRECTOR_V3_SPINE_TOPOLOGY_CANARY_PASSED" if technical and creative else "DIRECTOR_V3_SPINE_TOPOLOGY_CANARY_FAILED"
    failure_summary = {s["scene_id"]: {"spine_error_codes": sorted({_t(e.get("code")) for e in s["spine"]["protocol"].get("errors", [])}), "skeleton_error_codes": sorted({_t(e.get("code")) for e in s["skeleton"]["protocol"].get("errors", [])})} for s in scenes}
    real = {"schema_version": "director-quality-v3-spine-topology-canary-real-v1", "status": status, "base_commit": head, "authorized_calls": 6, "attempted_spine_calls": total_spine if not args.replay_existing else 0, "attempted_skeleton_calls": total_skeleton if not args.replay_existing else 0, "original_captured_spine_calls": 3, "original_captured_skeleton_calls": 3, "replay_provider_calls": 0 if args.replay_existing else None, "successful_http_calls": sum(bool(s["spine_raw_response"]) + bool(s["skeleton_raw_response"]) for s in scenes), "creative_generation_count": total_spine + total_skeleton if not args.replay_existing else 6, "transport_retry_count": 0, "semantic_retry_count": 0, "format_retry_count": 0, "repair_retry_count": 0, "scenes": scenes, "failure_summary": failure_summary, "counts": counts, "distinctiveness": {"scene_count": 3, "spine_signatures": spine_signatures, "role_sequences": [list(x) for x in role_sequences], "hard_template_leakage": hard_template}, "side_effects": {"atomic_expansion": 0, "shot_architecture": 0, "shotplan": 0, "storyboard": 0, "image": 0, "video": 0, "media": 0, "storage": 0, "shadow": 0}, "ready_for_atomic_expansion_canary": status.endswith("PASSED"), "atomic_expansion_canary_authorized": False, "ready_for_production_shotplan": False, "human_preference": "NOT_RECORDED"}; _write(ART / "director-quality-v3-spine-topology-canary-real.json", real); _write(ART / "director-quality-v3-spine-topology-canary-binding.json", {s["scene_id"]: s["binding"] for s in scenes}); _write(ART / "director-quality-v3-spine-topology-canary-spine-qa.json", {s["scene_id"]: s["spine"]["director_qa"] for s in scenes}); _write(ART / "director-quality-v3-spine-topology-canary-topology-qa.json", {s["scene_id"]: s["skeleton"]["topology_qa"] for s in scenes}); _write(ART / "director-quality-v3-spine-topology-canary-distinctiveness.json", real["distinctiveness"]); _write(ART / "director-quality-v3-spine-topology-canary-human-review-package.json", {"status": status, "human_review_pending": True, "ready_for_atomic_expansion_canary": real["ready_for_atomic_expansion_canary"], "ready_for_production_shotplan": False, "briefs": [str(p) for p in sorted(OUT.glob("*-spine-topology-brief.md"))]})
    report_spine_calls = 3 if args.replay_existing else total_spine; report_skeleton_calls = 3 if args.replay_existing else total_skeleton; report = f"# Director Quality V3 — Spine → Topology Canary\n\n**Status:** `{status}`\n\n## Baseline Audit\n\n- Frozen cohort: 3 approved Strategy Authority scenes; base commit `{EXPECTED_HEAD}`.\n- System prompts, contracts and six request templates were frozen before the first call.\n- No old Shot Architecture, ShotPlan, Storyboard or media output was supplied to either provider prompt.\n\n## Final As-Built Verification\n\n- Original real MiMo calls: **{report_spine_calls + report_skeleton_calls}** (Spine {report_spine_calls}, Skeleton {report_skeleton_calls}); replay provider calls: **{0 if args.replay_existing else 'n/a'}**; retries: **0**.\n- Spine Protocol/Authority/Coverage: {counts['spine_protocol']}/3 / {counts['spine_authority']}/3 / {counts['spine_coverage']}/3; Strong/Usable: {counts['spine_strong_or_usable']}/3; future leaks: {counts['spine_future_leak']}; mechanical beat→segment: {counts['spine_mechanical']}.\n- Skeleton Protocol/Authority/Coverage: {counts['skeleton_protocol']}/3 / {counts['skeleton_authority']}/3 / {counts['skeleton_coverage']}/3; forbidden execution fields: {counts['forbidden_execution_fields']}; canonical graph refs: {counts['canonical_graph_refs']}.\n- Reaction nodes: {counts['reaction_nodes']}; missing semantic stimulus: {counts['reaction_semantic_missing']}; Binder edges: {counts['binding_resolved_edges']}; ambiguous/missing/future/self-edge: {counts['binding_ambiguous']}/{counts['binding_missing']}/{counts['binding_future_invalid']}/{counts['binding_self_edge']}.\n- Topology Strong/Usable: {counts['topology_strong_or_usable']}/3; mechanical beat→node: {counts['topology_mechanical']}; hard template leakage: `{hard_template}`.\n\n## Scene Results\n\n" + "\n".join(f"- `{s['scene_id']}`: Spine={s['spine']['director_qa']['signal']}, segments={len(_l(s['spine'].get('ir', {}).get('segments')))}; Topology={s['skeleton']['topology_qa']['signal']}, nodes={len(_l(s['skeleton'].get('ir', {}).get('nodes')))}; Binder={s['binding']['binding_status']}" for s in scenes) + "\n\n## Release Boundary\n\n`READY_FOR_ATOMIC_EXPANSION_CANARY=" + str(real["ready_for_atomic_expansion_canary"]).lower() + "`\n`ATOMIC_EXPANSION_CANARY_AUTHORIZED=false`\n`READY_FOR_PRODUCTION_SHOTPLAN=false`\n`READY_FOR_STORYBOARD=false`\n`READY_FOR_MEDIA=false`\n\n## Failure Summary\n\n" + "\n".join(f"- `{sid}`: Spine codes={item['spine_error_codes']}; Skeleton codes={item['skeleton_error_codes']}" for sid, item in failure_summary.items()) + "\n"; (ART / "director-quality-v3-spine-topology-canary-report.md").write_text(report, encoding="utf-8")
    pointer.setdefault("shot_architecture", {}).setdefault("generation_architecture_redesign", {})["spine_topology_canary"] = {"status": "PASSED" if status.endswith("PASSED") else "FAILED", "attempted_spine_calls": 3, "attempted_skeleton_calls": 3, "replay_provider_calls": 0 if args.replay_existing else None, "atomic_expansion_canary_authorized": False, "production_shotplan": "HOLD"}; _write(ART / "director-quality-v3-current-stage-authority.json", pointer)
    print(json.dumps({"status": status, "counts": counts, "provider_calls": total_spine + total_skeleton, "report": str(ART / "director-quality-v3-spine-topology-canary-report.md")}, ensure_ascii=False, indent=2)); return 0 if status.endswith("PASSED") else 1

if __name__ == "__main__": raise SystemExit(main())
