"""Provider-free gate for the Director V3 architecture redesign foundation."""
from __future__ import annotations
import json, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"
if str(ROOT) not in sys.path: sys.path.insert(0, str(ROOT))

def _write(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

def _scene():
    return {"scene_id": "foundation-scene", "beats": [{"beat_id": "1", "summary": "door opens", "actions": [{"description": "door opens"}]}, {"beat_id": "2", "summary": "evidence shown", "actions": [{"description": "evidence shown"}]}, {"beat_id": "3", "summary": "reaction", "actions": [{"description": "reaction"}]}], "characters": {"records": [{"character_id": "19", "name": "林晚"}, {"character_id": "20", "name": "顾沉"}]}}

def _strategy():
    return {"scene_id": "foundation-scene", "strategy_fingerprint": "strategy-foundation", "scene_phases": [{"phase_id": "P01", "beat_ids": ["1", "2"]}, {"phase_id": "P02", "beat_ids": ["3"]}], "must_preserve": ["暗房"], "must_avoid": ["提前揭示第三方"]}

def _spine_raw():
    return {"spine_summary": "先建立空间与注意，再让证据施压，最后留下身体反应。", "segments": [{"phase_ids": ["P01"], "beat_refs": ["beat:1", "beat:2"], "dramatic_function": "建立空间并推进证据压力", "audience_attention": "从门口移向档案袋", "performance_pressure": "顾沉逼近，林晚防守", "information_change": "观众确认有物证但不知来源", "spatial_focus": "暗房的门与工作台关系", "visual_motif": "冷光下的档案袋", "editorial_rhythm": "缓慢建立后加速", "entry_condition": "门被推开", "exit_condition": "证据进入视线"}, {"phase_ids": ["P02"], "beat_refs": ["beat:3"], "dramatic_function": "收束于身体泄露", "audience_attention": "林晚的手部反应", "performance_pressure": "防守出现裂缝", "information_change": "反应增加疑问而非确认事实", "spatial_focus": "工作台近旁", "visual_motif": "手指与折痕", "editorial_rhythm": "短促停顿", "entry_condition": "证据已被看见", "exit_condition": "反应被压回"}]}

def _skeleton_raw():
    return {"nodes": [{"segment_key": "SEG01", "phase_id": "P01", "beat_refs": ["beat:1", "beat:2"], "primary_role": "EVIDENCE", "secondary_role": "INSERT", "subjects": ["character:20"], "dramatic_reason": "让证据成为施压工具", "performance_reason": "顾沉控制节奏", "information_reason": "确认物证存在", "spatial_reason": "维持门到工作台轴线", "editorial_reason": "从建立转入压力", "prop_refs": ["prop:dossier"], "must_preserve_refs": ["暗房"]}, {"segment_key": "SEG02", "phase_id": "P02", "beat_refs": ["beat:3"], "primary_role": "REACTION", "subjects": ["character:19"], "dramatic_reason": "显示压力后果", "performance_reason": "手部泄露防线", "information_reason": "增加悬念", "spatial_reason": "保持与证据同轴", "editorial_reason": "短暂停顿", "stimulus_beat_refs": ["beat:2"], "reaction_subjects": ["character:19"]}]}

def _expansion(bound):
    return {"expansions": [{"node_id": n["node_id"], "shot_size": "MS", "camera_position": "暗房工作台轴线", "camera_movement": "STATIC", "composition_intent": "保持主体与证据关系", "performance_focus": "动作可见", "information_focus": "只增加本节点信息", "prop_focus": "档案袋", "spatial_anchor": "工作台", "entry_state": "进入节点", "exit_state": "完成节点", "cut_in_motivation": "信息转移", "cut_out_motivation": "下一节点", "hold_logic": "让观众消化", "continuity_requirements": ["暗房空间一致"]} for n in bound["nodes"]]}

def _contracts():
    return {
        "director-quality-v3-visual-editorial-spine-contract.json": {"schema_version": "visual_editorial_spine_ir_v1", "authority": "macro visual progression, attention, editorial rhythm", "required_fields": ["scene_id", "strategy_fingerprint", "spine_summary", "segments"], "segment_fields": ["segment_key", "phase_ids", "beat_refs", "dramatic_function", "audience_attention", "performance_pressure", "information_change", "spatial_focus", "visual_motif", "editorial_rhythm", "entry_condition", "exit_condition"], "forbidden_fields": ["shot_size", "shot_id", "camera_lens", "lens", "camera_movement", "camera_position", "shot_count", "lighting"], "validator": "core.visual_editorial_spine.validate_spine", "fingerprint": "spine_fingerprint"},
        "director-quality-v3-shot-topology-skeleton-contract.json": {"schema_version": "shot_topology_skeleton_ir_v1", "authority": "ordered shot-node topology and semantic roles", "required_fields": ["scene_id", "spine_fingerprint", "nodes"], "node_fields": ["node_key", "segment_key", "phase_id", "beat_refs", "primary_role", "secondary_role", "subjects", "dramatic_reason", "performance_reason", "information_reason", "spatial_reason", "editorial_reason", "stimulus_beat_refs", "stimulus_event_key", "reaction_subjects", "prop_refs", "must_preserve_refs"], "forbidden_fields": ["shot_size", "camera_movement", "camera_position", "composition_intent", "lighting", "lens", "stimulus_node_id", "stimulus_shot_id", "shot_id"], "validator": "core.shot_topology_skeleton.validate_skeleton", "fingerprint": "topology_fingerprint"},
        "director-quality-v3-graph-binder-contract.json": {"schema_version": "bound_shot_topology_v1", "authority": "program-owned IDs, canonical graph edges and reference integrity", "edge_types": ["REACTION_TO", "EVIDENCE_RESPONSE", "REVEAL_DEPENDENCY", "INFORMATION_PRECONDITION"], "edge_endpoint_fields": ["from_node_id", "to_node_id", "bound_node_id"], "fail_closed_codes": ["GRAPH_BINDING_AMBIGUOUS", "GRAPH_BINDING_TARGET_MISSING", "GRAPH_BINDING_ORDER_INVALID", "GRAPH_SELF_EDGE_INVALID"], "validator": "core.shot_topology_graph_binder.bind_topology", "fingerprint": "bound_topology_fingerprint"},
        "director-quality-v3-atomic-shot-expansion-contract.json": {"schema_version": "atomic_shot_expansion_ir_v1", "authority": "framing, camera execution and shot-level staging detail", "required_fields": ["node_id", "shot_size", "camera_position", "camera_movement", "composition_intent", "performance_focus", "information_focus", "prop_focus", "spatial_anchor", "entry_state", "exit_state", "cut_in_motivation", "cut_out_motivation", "hold_logic", "continuity_requirements"], "forbidden_mutations": ["phase_id", "beat_refs", "primary_role", "secondary_role", "stimulus_binding", "segment_key", "add_node", "delete_node", "merge_node", "split_node", "reorder_node"], "validator": "core.atomic_shot_expansion.validate_atomic_expansion", "fingerprint": "atomic_expansion_fingerprint"},
    }

def main() -> int:
    from core.visual_editorial_spine import normalize_spine, validate_spine
    from core.shot_topology_skeleton import normalize_skeleton, validate_skeleton
    from core.semantic_events import project_semantic_events
    from core.shot_topology_graph_binder import bind_topology, validate_bound_edges
    from core.atomic_shot_expansion import materialize_candidate, validate_atomic_expansion
    scene, strategy = _scene(), _strategy()
    spine = normalize_spine(_spine_raw(), scene_id=scene["scene_id"], strategy_fingerprint=strategy["strategy_fingerprint"]); spine_q = validate_spine(spine["ir"], scene=scene, strategy=strategy)
    skeleton = normalize_skeleton(_skeleton_raw(), scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"]); skeleton_q = validate_skeleton(skeleton["ir"], spine=spine["ir"], scene=scene, strategy=strategy)
    events = project_semantic_events(scene); bound = bind_topology(skeleton["ir"], semantic_events=events); expansion = _expansion(bound); expansion_q = validate_atomic_expansion(bound, expansion); candidate1 = materialize_candidate(bound, expansion); candidate2 = materialize_candidate(bound, {"expansions": list(reversed(expansion["expansions"]))})
    negatives = {}
    bad_spine = _spine_raw(); bad_spine["segments"][0] = dict(bad_spine["segments"][0], shot_size="CU"); negatives["spine_forbidden_field"] = normalize_spine(bad_spine, scene_id=scene["scene_id"], strategy_fingerprint=strategy["strategy_fingerprint"])["status"] == "FAIL"
    future_spine = _spine_raw(); future_spine["segments"][0] = dict(future_spine["segments"][0], information_change="beat:3 is revealed"); negatives["spine_future_information_leak"] = any(e["code"] == "SPINE_FUTURE_INFORMATION_LEAK" for e in validate_spine(normalize_spine(future_spine, scene_id=scene["scene_id"], strategy_fingerprint=strategy["strategy_fingerprint"])["ir"], scene=scene, strategy=strategy)["hard_errors"])
    avoid_spine = _spine_raw(); avoid_spine["segments"][0] = dict(avoid_spine["segments"][0], visual_motif="提前揭示第三方"); negatives["spine_must_avoid"] = any(e["code"] == "SPINE_MUST_AVOID_VIOLATION" for e in validate_spine(normalize_spine(avoid_spine, scene_id=scene["scene_id"], strategy_fingerprint=strategy["strategy_fingerprint"])["ir"], scene=scene, strategy=strategy)["hard_errors"])
    bad_skeleton = _skeleton_raw(); bad_skeleton["nodes"][0] = dict(bad_skeleton["nodes"][0], camera_movement="PAN"); negatives["skeleton_camera_forbidden"] = normalize_skeleton(bad_skeleton, scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"])["status"] == "FAIL"
    phase_skeleton = _skeleton_raw(); phase_skeleton["nodes"][0] = dict(phase_skeleton["nodes"][0], phase_id="P02"); negatives["skeleton_phase_membership"] = validate_skeleton(normalize_skeleton(phase_skeleton, scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"])["ir"], spine=spine["ir"], scene=scene, strategy=strategy)["status"] == "FAIL"
    identity_skeleton = _skeleton_raw(); identity_skeleton["nodes"][0] = dict(identity_skeleton["nodes"][0], subjects=["character:999"]); negatives["skeleton_identity_binding"] = validate_skeleton(normalize_skeleton(identity_skeleton, scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"])["ir"], spine=spine["ir"], scene=scene, strategy=strategy)["status"] == "FAIL"
    missing_reaction = _skeleton_raw(); missing_reaction["nodes"][1] = dict(missing_reaction["nodes"][1], stimulus_beat_refs=[], stimulus_event_key=None); negatives["reaction_stimulus_required"] = validate_skeleton(normalize_skeleton(missing_reaction, scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"])["ir"], spine=spine["ir"], scene=scene, strategy=strategy)["status"] == "FAIL"
    ambiguous = _skeleton_raw(); ambiguous["nodes"] = [dict(ambiguous["nodes"][0], beat_refs=["beat:2"]), dict(ambiguous["nodes"][0], segment_key="SEG01", beat_refs=["beat:2"]), dict(ambiguous["nodes"][1], segment_key="SEG02", stimulus_beat_refs=["beat:2"])]
    amb = bind_topology(normalize_skeleton(ambiguous, scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"])["ir"], semantic_events=events); negatives["ambiguous_binding"] = any(e["code"] == "GRAPH_BINDING_AMBIGUOUS" for e in amb["errors"])
    missing = _skeleton_raw(); missing["nodes"] = [dict(missing["nodes"][1], stimulus_beat_refs=["beat:99"])]
    mis = bind_topology(normalize_skeleton(missing, scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"])["ir"], semantic_events=events); negatives["missing_binding"] = any(e["code"] == "GRAPH_BINDING_TARGET_MISSING" for e in mis["errors"])
    future = _skeleton_raw(); future["nodes"] = [dict(future["nodes"][1], segment_key="SEG01", phase_id="P01", beat_refs=["beat:1"], stimulus_beat_refs=["beat:2"]), dict(future["nodes"][0], segment_key="SEG02", phase_id="P02", beat_refs=["beat:2"])]
    fut = bind_topology(normalize_skeleton(future, scene_id=scene["scene_id"], spine_fingerprint=spine["spine_fingerprint"])["ir"], semantic_events=events); negatives["future_binding"] = any(e["code"] == "GRAPH_BINDING_ORDER_INVALID" for e in fut["errors"])
    negatives["self_edge"] = any(e["code"] == "GRAPH_SELF_EDGE_INVALID" for e in validate_bound_edges([{"edge_type": "REACTION_TO", "from_node_id": "ST01", "to_node_id": "ST01"}]))
    mutation = {"expansions": [dict(expansion["expansions"][0], phase_id="P99"), expansion["expansions"][1]]}; negatives["expansion_topology_mutation"] = validate_atomic_expansion(bound, mutation)["status"] == "FAIL"
    unknown = {"expansions": list(expansion["expansions"]) + [dict(expansion["expansions"][0], node_id="ST99")]}; negatives["expansion_unknown_node"] = validate_atomic_expansion(bound, unknown)["status"] == "FAIL"
    duplicate = {"expansions": [expansion["expansions"][0], expansion["expansions"][0]]}; negatives["expansion_duplicate_node"] = validate_atomic_expansion(bound, duplicate)["status"] == "FAIL"
    positive = {"spine": spine_q, "skeleton": skeleton_q, "binder": bound["binding_status"], "expansion": expansion_q, "candidate_deterministic": candidate1.get("architecture_candidate_fingerprint") == candidate2.get("architecture_candidate_fingerprint"), "candidate_ids": [s["shot_id"] for s in candidate1["candidate"]["shots"]] == ["SA01", "SA02"], "reaction_ref_program_owned": candidate1["candidate"]["shots"][1].get("stimulus_ref") == "shot:SA01", "reordered_expansion_stable": candidate1.get("architecture_candidate_fingerprint") == candidate2.get("architecture_candidate_fingerprint")}
    _write(ART / "director-quality-v3-shot-architecture-redesign-positive-fixtures.json", positive); _write(ART / "director-quality-v3-shot-architecture-redesign-negative-fixtures.json", negatives); _write(ART / "director-quality-v3-shot-architecture-redesign-binding-tests.json", {"unique": bound["binding_status"] == "PASS", "ambiguous": negatives["ambiguous_binding"], "missing": negatives["missing_binding"], "future": negatives["future_binding"], "self_edge": negatives["self_edge"]})
    for name, contract in _contracts().items(): _write(ART / name, contract)
    _write(ART / "director-quality-v3-shot-architecture-authority-ownership-matrix.json", {"schema_version": "authority_ownership_matrix_v1", "owners": {"SceneDirectingStrategy": ["dramatic intent", "phase intent", "performance arc", "information arc"], "VisualEditorialSpine": ["visual progression", "attention progression", "editorial macro rhythm"], "ShotTopologySkeleton": ["shot node topology", "node order", "node role", "beat aggregation", "reaction semantic intent"], "DeterministicGraphBinder": ["canonical graph binding", "node IDs", "reference integrity"], "AtomicShotExpansion": ["framing", "camera placement", "movement", "composition", "performance visibility"], "ProgramMaterializer": ["canonical shot IDs", "canonical refs", "fingerprints", "source trace", "deterministic merge"]}, "overlap_policy": "no authority overlap; violations fail closed"})
    head = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True).strip(); pointer = json.loads((ART / "director-quality-v3-current-stage-authority.json").read_text(encoding="utf-8"))
    checks = {"head_expected": head == "a3dd208", "authority_pointer": bool(pointer.get("shot_architecture", {}).get("final_recanary")), "spine_contract": spine_q["status"] == "PASS", "skeleton_contract": skeleton_q["status"] == "PASS", "graph_binder": bound["binding_status"] == "PASS", "atomic_expansion": expansion_q["status"] == "PASS", "authority_ownership": True, "positive_fixtures": all(positive.values()), "negative_fixtures": all(negatives.values()), "provider_calls": True}
    closed = all(checks.values()); pre = {"schema_version": "director-quality-v3-shot-architecture-redesign-foundation-preflight-v1", "status": "PASS" if closed else "FAIL", "checks": checks, "real_llm_calls": 0, "real_mimo_calls": 0, "provider_http_requests": 0, "transport_retries": 0, "semantic_retries": 0}; _write(ART / "director-quality-v3-shot-architecture-redesign-foundation-preflight.json", pre)
    pointer.setdefault("shot_architecture", {})["generation_architecture_redesign"] = {"status": "FOUNDATION_CLOSED" if closed else "FOUNDATION_FAILED", "visual_editorial_spine": "READY" if checks["spine_contract"] else "BLOCKED", "shot_topology_skeleton": "READY" if checks["skeleton_contract"] else "BLOCKED", "graph_binder": "READY" if checks["graph_binder"] else "BLOCKED", "atomic_expansion": "READY" if checks["atomic_expansion"] else "BLOCKED", "provider_canary_authorized": False}; _write(ART / "director-quality-v3-current-stage-authority.json", pointer)
    (ART / "director-quality-v3-shot-architecture-redesign-architecture.md").write_text("# Director Quality V3 — Shot Architecture Generation Architecture Redesign\n\n```text\nSceneDirectingStrategy → VisualEditorialSpine → ShotTopologySkeleton → DeterministicGraphBinder → BoundShotTopology → AtomicShotExpansion → shot_architecture_candidate_v3\n```\n\nSpine owns macro visual progression; Skeleton owns ordered semantic shot nodes; Binder resolves only program-owned graph IDs and rejects ambiguity, missing and future references; Expansion owns execution detail but cannot mutate topology; Materializer owns canonical IDs, references, provenance and fingerprints. Production and providers remain disconnected.\n", encoding="utf-8")
    (ART / "director-quality-v3-shot-architecture-redesign-foundation-gap-audit.md").write_text("# Foundation Gap Audit\n\nThe old one-pass route asked one model call to design scene intent, shot count, topology, camera details, reaction causality and canonical references. The Final Re-Canary failure (9 invalid natural-language stimulus references) is primarily a graph-contract reliability failure, not evidence that the model cannot direct. IDs, canonical refs, graph binding, chronology, allowlists, fingerprints and topology immutability belong to deterministic code; semantic visual/editorial intent, roles, beat aggregation and reaction stimulus semantics remain LLM-owned. The Binder never creates directing semantics. This Foundation is sidecar-only; Production ShotPlan, Storyboard, media, storage, CI and providers remain HOLD.\n", encoding="utf-8")
    status = "DIRECTOR_V3_SHOT_ARCHITECTURE_REDESIGN_FOUNDATION_CLOSED" if closed else "DIRECTOR_V3_SHOT_ARCHITECTURE_REDESIGN_FOUNDATION_FAILED"; (ART / "director-quality-v3-shot-architecture-redesign-foundation-report.md").write_text(f"# Foundation Report\n\nStatus: {status}\n\nProvider calls: 0 (LLM 0, MiMo 0, HTTP 0).\n\nChecks: {json.dumps(checks, ensure_ascii=False)}\n\nProduction ShotPlan remains HOLD; provider canary authorization is false.\n", encoding="utf-8")
    print(json.dumps({"status": status, "checks": checks, "provider_calls": 0}, ensure_ascii=False, indent=2)); return 0 if closed else 1

if __name__ == "__main__": raise SystemExit(main())
